export const NOTIFICATION_ORDER_ANSWER = 'NOTIFICATION_ORDER_ANSWER';
export const NOTIFICATION_CHAT_MESSAGE = 'NOTIFICATION_CHAT_MESSAGE';
export const NOTIFICATION_PERFORM_SERVICE = 'NOTIFICATION_PERFORM_SERVICE';
export const NOTIFICATION_ORDER_QUESTION = 'NOTIFICATION_ORDER_QUESTION';
export const NOTIFICATION_ORDER_TRACKING = 'NOTIFICATION_ORDER_TRACKING';
export const NOTIFICATION_ORDER_NEAR_RECOMMENDED = 'NOTIFICATION_ORDER_NEAR_RECOMMENDED';
export const NOTIFICATION_REPUTATION = 'NOTIFICATION_REPUTATION';
export const NOTIFICATION_RATE = 'NOTIFICATION_RATE';
